language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t kildares/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true kildares/docker-react npm run test